name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Configure and build with CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      - name: Rename release folder
        shell: pwsh
        run: |
          $releaseDir = "build/Release"
          $newDir = "EnhancedDisplaySwitch"
          if (Test-Path $releaseDir) {
              Rename-Item -Path $releaseDir -NewName $newDir
          } else {
              Write-Error "Release folder not found!"
              exit 1
          }

      - name: Zip binaries folder
        run: |
          $zipFile = "build/EnhancedDisplaySwitch_msvc_64.zip"
          $folder = "build/EnhancedDisplaySwitch"
          Compress-Archive -Path $folder -DestinationPath $zipFile
        shell: pwsh
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EnhancedDisplaySwitch_msvc_64
          path: build/EnhancedDisplaySwitch_msvc_64.zip

